package com.shivani.notepad.entity;

import jakarta.persistence.*;
import lombok.Data;
import lombok.NoArgsConstructor;
import lombok.AllArgsConstructor;
import java.time.LocalDateTime;
/**
 * Represents an application user.
 *
 * This entity stores authentication credentials and basic user
 * information required for login and account management.
 *
 * Maps to the 'users' table in the database.
 */
@Entity
@Table(name = "users")
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User {
    /**
     * Primary key.
     * Automatically generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Integer id;
    /**
     * Unique username used for user identification.
     */
    @Column(nullable = false, unique = true)
    private String username;
    /**
     * User's unique email address.
     * Used for account verification and communication.
     */
    @Column(nullable = false, unique = true)
    private String email;
    /**
     * Stores the user's encrypted password.
     * Plain-text passwords should never be stored.
     */
    @Column(nullable = false)
    private String password;
    /**
     * Timestamp indicating when the account was created.
     * Set automatically during the initial persistence.
     */
    @Column(updatable = false)
    /**
     * Timestamp indicating when the account was created.
     * Set automatically during the initial persistence.
     */
    private LocalDateTime createdAt;
    /**
     * Timestamp indicating the most recent account update.
     * Automatically updated whenever the entity is modified.
     */
    private LocalDateTime updatedAt;
    /**
     * Initializes audit fields before the entity is inserted
     * into the database.
     */
    @PrePersist
    protected void onCreate(){
        createdAt = LocalDateTime.now();
        updatedAt = LocalDateTime.now();
    }
    /**
     * Updates the modification timestamp before any update
     * operation is executed.
     */
    @PreUpdate
    protected void onUpdate(){
        updatedAt = LocalDateTime.now();
    }
    /**
     * Whether the user has confirmed their email address via the
     * verification link sent at registration. Login is blocked (via
     * Spring Security's enabled flag) until this is true — see
     * CustomUserDetailsService.
     */
    @Column(nullable = false)
    private boolean emailVerified = false;
    /**
     * One-time token emailed to the user at registration, consumed by
     * the /verify-email endpoint. Nulled out once verification succeeds.
     */
    @Column(nullable = true, unique = true)
    private String verificationToken;
    /**
     * One-time token emailed to the user when they request a password
     * reset. Nulled out once the reset is completed (or expires).
     */
    @Column(nullable = true, unique = true)
    private String resetToken;
    /**
     * Expiry timestamp for resetToken — tokens are valid for 30 minutes
     * from generation, after which the reset link no longer works even
     * if the token string is still known.
     */
    @Column(nullable = true)
    private LocalDateTime resetTokenExpiry;

    @Column(nullable = false)
    private boolean emailRemindersEnabled = true;

    @Column(nullable = false)
    private boolean dailySummaryEnabled = true;
}
